name: mshqc
channels:
  - conda-forge
  - defaults
dependencies:
  
  - python>=3.8
  - pip
  - cmake>=3.18
  - ninja
  - pkg-config 
  - c-compiler       
  - cxx-compiler
  - llvm-openmp
  - mkl              
  - mkl-include      
  - eigen
  - libcint          
  - tblis            
  - hdf5
  - llvmdev     # Injeksi MLIR/LLVM backend
  - mlir        # Infrastruktur graf kompilator             
  - jemalloc         
  - nanobind         
  - numpy>=1.20
  - scipy
  - pytest
