[build-system]
requires = ["setuptools>=42", "scikit-build>=0.13", "cmake>=3.18", "ninja", "nanobind>=1.9"]
build-backend = "setuptools.build_meta"

[project]
name = "mshqc"
version = "1.0.0"
description = "Modern Quantum Chemistry Library (Pure MLIR JIT Backend)"
authors = [
    { name = "Muhamad Syahrul Hidayat", email = "author@example.com" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20",
    "scipy>=1.7"
]

[tool.setuptools]
packages = ["mshqc"]
package-dir = {"" = "python"}
