jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # =========================================================================
    # SUNTIKKAN INI: Beri izin tulis (write) ke bot agar bisa push balik .whl
    # =========================================================================
    permissions:
      contents: write

    steps:
    - name: Checkout Private Source Code
      uses: actions/checkout@v3
      # Biarkan polosan tanpa 'with: token:' agar menggunakan token bawaan yang sudah diberi izin write di atas